(()=>{
  const css=`
  .journey-hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;background:linear-gradient(135deg,#14232d,#1b3442);border:1px solid #314b5c;border-radius:18px;padding:24px;margin-bottom:18px}.journey-hero h2{font-size:34px;margin:3px 0 8px}.journey-hero p{max-width:780px;margin:0;color:#b9c8d2;line-height:1.55}.journey-badge{white-space:nowrap;padding:9px 13px;border-radius:999px;border:1px solid #56788b;background:#101a23;color:#d8e8f2;font-weight:700}.cat-filter{display:flex;gap:9px;flex-wrap:wrap;margin:0 0 18px}.cat-chip{padding:8px 13px;border:1px solid #405868;border-radius:999px;background:#182630;color:#dce8ef;font-weight:700;cursor:pointer}.cat-chip.active{background:#e6b95a;color:#18212a;border-color:#e6b95a}.journey-timeline{display:grid;gap:20px}.journey-card{background:#14232d;border:1px solid #314b5c;border-radius:16px;overflow:hidden;box-shadow:0 8px 24px rgba(0,0,0,.18)}.journey-copy{padding:20px}.journey-meta{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.journey-meta span{font-size:12px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;padding:6px 9px;border-radius:999px;background:#203746;border:1px solid #395666}.journey-copy h3{font-size:27px;margin:7px 0 12px}.journey-copy p{line-height:1.6;color:#d0dde5}.journey-note{margin-top:14px;padding:14px 16px;border-left:3px solid #e6b95a;background:#101b23;border-radius:8px;color:#d8e5ec}.journey-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:10px;background:#0a1117}.journey-gallery img{width:100%;height:330px;object-fit:cover;border-radius:10px;background:#111}.journey-video{padding:10px;background:#0a1117}.journey-video video{display:block;width:100%;max-height:520px;object-fit:contain;border-radius:10px;background:#000}.journey-error{display:none;padding:18px;color:#ffccd2;background:#3e1d24}.journey-future{border:1px dashed #456172;background:#111d25;border-radius:14px;padding:18px;color:#9eb2bf}.journey-entry[hidden]{display:none!important}@media(max-width:850px){.journey-hero{display:block}.journey-badge{display:inline-block;margin-top:16px}.journey-gallery{grid-template-columns:1fr}.journey-gallery img{height:auto;max-height:520px}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const nav=document.querySelector('nav'); if(!nav||document.getElementById('journey')) return;
  const btn=document.createElement('button');btn.className='tab';btn.dataset.page='journey';btn.textContent='Journey';
  const first=nav.querySelector('.tab'); first?first.after(btn):nav.appendChild(btn);
  const section=document.createElement('section');section.className='page';section.id='journey';
  section.innerHTML=`
    <div class="journey-hero"><div><div class="kicker">OUR CATS • LIFE IN PICTURES & VIDEO</div><h2>Journey</h2><p>A growing timeline for Narlia, Dante and Amara, plus the cat daddies. Memories stay attached to their real date and age, so older photos can be added later without losing the story.</p></div><div class="journey-badge">Growing with them 🐾</div></div>
    <div class="cat-filter"><span class="cat-chip active">All cats</span><span class="cat-chip">Narlia</span><span class="cat-chip">Dante</span><span class="cat-chip">Amara</span><span class="cat-chip">Dante & Amara</span></div>
    <div class="journey-timeline">
      <article class="journey-entry" data-cat="Dante & Amara" data-date="2026-08-24"><div class="journey-card"><div class="journey-gallery"><img src="media/kitten-early-01.jpg?v=1" loading="lazy" alt="Early kitten photo, Dante or Amara"><img src="media/kitten-early-02.jpg?v=1" loading="lazy" alt="Early kitten photo, Dante or Amara"><img src="media/kitten-early-03.jpg?v=1" loading="lazy" alt="Early kitten photo, Dante or Amara"><img src="media/kitten-early-04.jpg?v=1" loading="lazy" alt="Early kitten photo, Dante or Amara"></div><div class="journey-copy"><div class="journey-meta"><span>Dante or Amara</span><span>Early days</span><span>Identity not yet confirmed</span></div><h3>Early kitten gallery</h3><p>These are part of Dante and Amara's early story. They stay shared until their individual identities are confirmed.</p><div class="journey-note"><b>Identification guide:</b> Amara is lilac. Dante is developing warmer brown/chocolate colouring. New uploads get a first-pass guess before confirmation.</div></div></div></article>
      <article class="journey-entry" data-cat="Dante & Amara" data-date="2026-08-24"><div class="journey-card"><div class="journey-video"><video controls playsinline preload="metadata" src="media/kitten-early-video-01.mp4?v=1"></video><div class="journey-error">Video could not load. The rest of the dashboard is unaffected.</div></div><div class="journey-copy"><div class="journey-meta"><span>Dante or Amara</span><span>Early days</span><span>Video</span><span>Identity not yet confirmed</span></div><h3>Early kitten video</h3><p>Saved into their shared early-days Journey until the kitten and event details are confirmed.</p></div></div></article>
      <article class="journey-entry" data-cat="Dante" data-date="2026-08-24"><div class="journey-card"><div class="journey-video"><video controls playsinline preload="metadata" src="media/dante-first-solid-food.mp4?v=1"></video><div class="journey-error">Video could not load. The rest of the dashboard is unaffected.</div></div><div class="journey-copy"><div class="journey-meta"><span>Dante</span><span>4 weeks old</span><span>24 Aug 2026</span><span>Milestone</span></div><h3>First solid food meal</h3><p>Dante had his first solid food meal and ate the lot. Afterwards he went back to mummy, suckled and had a drink, then fell asleep with a very full little belly.</p><div class="journey-note"><b>From Christine:</b> he ate it all, got a full belly, went back to mummy for a suckle and a drink, and fell asleep.</div></div></div></article>
      <div class="journey-future"><b>Built to backfill.</b> Earlier photos, videos, birthdays, coming-home memories and later GPS adventures can be inserted by their real date rather than upload order.</div>
    </div>`;
  const main=document.querySelector('main'); if(main) main.insertBefore(section,main.firstChild);
  btn.onclick=()=>{ if(typeof showPage==='function') showPage('journey'); };
  section.querySelectorAll('.cat-chip').forEach(chip=>chip.onclick=()=>{ section.querySelectorAll('.cat-chip').forEach(c=>c.classList.remove('active')); chip.classList.add('active'); const wanted=chip.textContent.trim(); section.querySelectorAll('.journey-entry').forEach(e=>e.hidden=!(wanted==='All cats'||e.dataset.cat===wanted)); });
  section.querySelectorAll('img').forEach(img=>img.onerror=()=>{img.style.display='none';});
  section.querySelectorAll('video').forEach(v=>v.addEventListener('error',()=>{const e=v.nextElementSibling;if(e)e.style.display='block';v.style.display='none';}));
})();