(()=>{
  const css=`
  .journey-hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;background:linear-gradient(135deg,#14232d,#1b3442);border:1px solid #314b5c;border-radius:18px;padding:24px;margin-bottom:18px}.journey-hero h2{font-size:34px;margin:3px 0 8px}.journey-hero p{max-width:780px;margin:0;color:#b9c8d2;line-height:1.55}.journey-badge{white-space:nowrap;padding:9px 13px;border-radius:999px;border:1px solid #56788b;background:#101a23;color:#d8e8f2;font-weight:700}.cat-filter{display:flex;gap:9px;flex-wrap:wrap;margin:0 0 18px}.cat-chip{padding:8px 13px;border:1px solid #405868;border-radius:999px;background:#182630;color:#dce8ef;font-weight:700;cursor:pointer}.cat-chip.active{background:#e6b95a;color:#18212a;border-color:#e6b95a}.journey-timeline{display:grid;gap:20px}.journey-card{background:#14232d;border:1px solid #314b5c;border-radius:16px;overflow:hidden;box-shadow:0 8px 24px rgba(0,0,0,.18)}.journey-copy{padding:20px}.journey-meta{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.journey-meta span{font-size:12px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;padding:6px 9px;border-radius:999px;background:#203746;border:1px solid #395666}.journey-copy h3{font-size:27px;margin:7px 0 12px}.journey-copy p{line-height:1.6;color:#d0dde5}.journey-note{margin-top:14px;padding:14px 16px;border-left:3px solid #e6b95a;background:#101b23;border-radius:8px;color:#d8e5ec}.journey-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:10px;background:#0a1117;justify-items:center}.journey-gallery img{display:block;width:auto;max-width:100%;height:auto;max-height:700px;object-fit:contain;border-radius:10px;background:#111}.journey-feature-photo{padding:10px;background:#0a1117;text-align:center}.journey-feature-photo img{display:block;width:auto;max-width:100%;height:auto;max-height:700px;margin:0 auto;object-fit:contain;border-radius:10px;background:#111}.journey-future{border:1px dashed #456172;background:#111d25;border-radius:14px;padding:18px;color:#9eb2bf}.journey-entry[hidden]{display:none!important}@media(max-width:850px){.journey-hero{display:block}.journey-badge{display:inline-block;margin-top:16px}.journey-gallery{grid-template-columns:1fr}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const nav=document.querySelector('nav'); if(!nav||document.getElementById('journey')) return;
  const btn=document.createElement('button');btn.className='tab';btn.dataset.page='journey';btn.textContent='Journey';
  const first=nav.querySelector('.tab'); first?first.after(btn):nav.appendChild(btn);
  const section=document.createElement('section');section.className='page';section.id='journey';
  const danteStill=window.DANTE_STILL||'media/dante-first-solid-food.jpg?v=5';
  section.innerHTML=`
    <div class="journey-hero"><div><div class="kicker">OUR CATS • LIFE IN PICTURES & STORIES</div><h2>Journey</h2><p>A growing photo timeline for Narlia, Dante and Amara, plus their cat daddies. Memories stay attached to their real date and age, so earlier photos and stories can be added later without losing the order.</p></div><div class="journey-badge">Growing with them 🐾</div></div>
    <div class="cat-filter"><span class="cat-chip active">All cats</span><span class="cat-chip">Narlia</span><span class="cat-chip">Dante</span><span class="cat-chip">Amara</span><span class="cat-chip">Dante & Amara</span></div>
    <div class="journey-timeline">
      <article class="journey-entry" data-cat="Dante & Amara" data-date="2026-08-25"><div class="journey-card"><div class="journey-feature-photo"><img src="media/2026-08-25-amara-dante-with-mum.webp?v=20260825-2" loading="eager" alt="Amara and Dante cuddled up with their mum"></div><div class="journey-copy"><div class="journey-meta"><span>Dante & Amara</span><span>25 Aug 2026</span><span>5 weeks old</span></div><h3>Cuddled up with mum</h3><p>Amara and Dante together, curled up with their mum. Amara is the lilac kitten in the foreground, correctly identified from the photo.</p></div></div></article>
      <article class="journey-entry" data-cat="Dante & Amara" data-date="2026-08-24"><div class="journey-card"><div class="journey-gallery"><img src="media/kitten-early-01.jpg?v=5" loading="lazy" alt="Early kitten photo, Dante or Amara"><img src="media/kitten-early-02.jpg?v=5" loading="lazy" alt="Early kitten photo, Dante or Amara"><img src="media/kitten-early-03.jpg?v=5" loading="lazy" alt="Early kitten photo, Dante or Amara"><img src="media/kitten-early-04.jpg?v=5" loading="lazy" alt="Early kitten photo, Dante or Amara"></div><div class="journey-copy"><div class="journey-meta"><span>Dante or Amara</span><span>Early days</span><span>Identity not yet confirmed</span></div><h3>Early kitten gallery</h3><p>These are part of Dante and Amara's early story. They stay shared until their individual identities are confirmed.</p><div class="journey-note"><b>Identification guide:</b> Amara is lilac. Dante is developing warmer brown/chocolate colouring. New uploads get a first-pass guess before confirmation.</div></div></div></article>
      <article class="journey-entry" data-cat="Dante" data-date="2026-08-24"><div class="journey-card"><div class="journey-feature-photo"><img src="${danteStill}" loading="eager" alt="Dante at four weeks having his first solid food meal"></div><div class="journey-copy"><div class="journey-meta"><span>Dante</span><span>4 weeks old</span><span>24 Aug 2026</span><span>Milestone</span></div><h3>First solid food meal</h3><p>Dante had his first solid food meal and ate the lot. Afterwards he went back to mummy, suckled and had a drink, then fell asleep with a very full little belly.</p><div class="journey-note"><b>From Christine:</b> he ate it all, got a full belly, went back to mummy for a suckle and a drink, and fell asleep.</div></div></div></article>
      <div class="journey-future"><b>Built to backfill.</b> Earlier photos, birthdays, coming-home memories, notes and later GPS adventures can be inserted by their real date rather than upload order.</div>
    </div>`;
  const main=document.querySelector('main'); if(main) main.insertBefore(section,main.firstChild);
  btn.onclick=()=>{ if(typeof showPage==='function') showPage('journey'); };
  section.querySelectorAll('.cat-chip').forEach(chip=>chip.onclick=()=>{ section.querySelectorAll('.cat-chip').forEach(c=>c.classList.remove('active')); chip.classList.add('active'); const wanted=chip.textContent.trim(); section.querySelectorAll('.journey-entry').forEach(e=>e.hidden=!(wanted==='All cats'||e.dataset.cat===wanted)); });
})();